---
name: cmpsc-203-spring-2021-practical3
break: true
indent: 4
---

# --> check the source code for various characteristics
# note that without an "--exact" the check is an "at least"
termfrequency:
        compute_tf_cookbook.py:
            ConfirmFileExists
            CountMultipleLineComments --language Python --count 7
            CountSingleLineComments --language Python --count 14
            MatchFileFragment --fragment "import string" --count 1 --exact
            MatchFileFragment --fragment "TODO" --count 0 --exact
            MatchFileFragment --fragment "with open" --count 1
            MatchFileFragment --fragment "global data" --count 3
            MatchFileFragment --fragment "global words" --count 3
            MatchFileFragment --fragment "as data_file" --count 1
            MatchFileFragment --fragment "word_freqs" --count 9
            MatchFileFragment --fragment "data = []" --count 1
            MatchFileFragment --fragment "words = []" --count 1
            MatchFileFragment --fragment "word_freqs = []" --count 1

tests:
        test_compute_tf_cookbook.py:
            ConfirmFileExists
            CountMultipleLineComments --language Python --count 5
            CountSingleLineComments --language Python --count 0
            MatchFileFragment --fragment "test_" --count 5
            MatchFileFragment --fragment "TODO" --count 0 --exact

tests:
        conftest.py:
            ConfirmFileExists
            MatchFileFragment --fragment "TODO" --count 0 --exact

tests:
        __init__.py:
            ConfirmFileExists
            MatchFileFragment --fragment "TODO" --count 0 --exact

# --> check the technical writing
writing/reflection.md:
    ConfirmFileExists
    CountFileWords --count 400
    CountMarkdownTags --tag "heading" --count 9 --exact
    CountMarkdownTags --tag "code_block" --count 1 --exact
    CountMarkdownTags --tag "list" --count 1 --exact
    MatchFileFragment --fragment "Add Your Name Here" --count 0 --exact
    MatchFileFragment --fragment "TODO" --count 0 --exact

# --> check the number of commits beyond a threshold
CountCommits --count 5
